languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Ak13a's site"
copyright = "© 2025 Diego Akira García Rojas"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["posts", "writeups", "projects", "about"]
  description = "Ak13a's personal blog and portfolio"

[params.author]
  name = "Ak13a"
  image = "img/pic.jpg"
  headline = "Comp. Sci. Student, Cybersecurity enthusiast, CTF Player"
  links = [
    { github = "https://github.com/Akira-13" },
    { linkedin = "https://www.linkedin.com/in/diego-akira-garc%C3%ADa-rojas-80b4b7299/" },
    { discord = "https://discordapp.com/users/1310587616462114849" },
    { email = "mailto:ak13a@tutamail.com" },
  ]
